version: "3.9"
services:
  stats-server:
    build: stats/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ewm-stats
    volumes:
      - postgres-data:/var/lib/postgresql/data
  ewm-service:
    build: ewm-service
    # image: ewm-service
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Duser.timezone=UTC
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5434/ewm
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      - ewm-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
  ewm-db:
    image: postgres:16
    container_name: postgres-ewm-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=ewm
    command: ["postgres", "-p", "5434"]
    ports:
      - "5434:5434"
    healthcheck:
      test: pg_isready -p 5434 -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    volumes:
      - postgres-ewm-data:/var/lib/postgresql/data
volumes:
  postgres-data:
  postgres-ewm-data:




