services:
  stats-server:
    build: stats/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL= jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME = postgres
      - SPRING_DATASOURCE_PASSWORD= 12345

  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_PASSWORD = 12345
      - POSTGRES_USER = postgres
      - POSTGRES_DB = ewm-stats


 # ewm-service:
 #   ports:
 #     - "8080:8080"
 #   environment:
 #     - CLIENT_URL = http://stats-server:9090
 #     - SPRING_DATASOURCE_URL= jdbc:postgresql://ewm-db:5432/ewm-main
 #     - SPRING_DATASOURCE_USERNAME = postgres
 #     - SPRING_DATASOURCE_PASSWORD= 12345

  # ewm-db:
  #  image: postgres:16.1
